### PR TITLE
Use inline phpcs rules instead of phpcs.xml

### PR DESCRIPTION
**Pull request by Log1x**
- **Opinionated change**: Lets us take a file out of version control while still maintaining near-identical linting rules.

### CODE REVIEW

**Comment by swalkinshaw** [comment]
Agreed this is better 👍

**Comment by austinpray** [comment]
I actually don’t like this change at all. I end up adding a ton of exclusions so third party plugins aren’t scanned. The rules as-is will scan the plugins dir. it doesn’t make sense to add a bunch of those exclusions as cli args in a json file.

**Comment by TangRufus** [comment]
> I actually don’t like this change at all.
Same here.

Having `phpcs.xml` is easier to use custom standards.

**Comment by austinpray** [comment]
Maybe we take this to revert town https://github.com/roots/bedrock/pull/461

**Pull request merged**
