### PR TITLE
Add environment vars for database collation, charset

### PR DESCRIPTION
**Pull request by michaeldyrynda**
Update application config to use the new environment configuration variables.

### CODE REVIEW

**Comment by swalkinshaw** [comment]
What's the use case for this? The idea behind config settings with env vars are:

1. They are "secret" and shouldn't be committed
2. They vary between environment

These definitely aren't secrets and they really *shouldn't* differ per environment. It could easily lead to issues if they did.

**Comment by michaeldyrynda** [comment]
I just felt it odd that everything else was configurable via env except these parameters, but I can see your point of view as well.

It was only because I was using [Herbert](http://getherbert.com/) and it was having issues with utf8mb4 collation that I went looking for a solution.

I suppose it's not something most would have to change, would some clearer documentation on this be more suitable?

**Comment by swalkinshaw** [comment]
Documentation around `utf8mb4` specifically? `utf8mb4` should the default nowadays and even WP [upgrades](https://make.wordpress.org/core/2015/04/02/the-utf8mb4-upgrade/) when its available.

**Comment by eimanavicius** [comment]
Why DB_PREFIX is not in .env.example file? But have environment var?
$table_prefix = env('DB_PREFIX') ?: 'wp_';

Maybe we should have these new vars with defaults?

**Comment by QWp6t** [comment]
@eimanavicius https://github.com/roots/bedrock/pull/261

**Comment by QWp6t** [comment]
I'm with swalk on this, but if there's demand for it, then it should follow the pattern in #261 for optional variables, i.e., it exists in the .env.example file, but it's commented out, and there is a default value for it defined in application.php. But again, that's only if there's a demand. These are variables that really shouldn't be changed between environments.

**Comment by swalkinshaw** [comment]
Yeah I'm going to close this in its current state for the reasons mentioned above.

**Comment by michaeldyrynda** [comment]
Thanks, folks. With regards to docs, I was referring to the additional variables that could be changed in `config/application.php`, but looking [here](https://roots.io/bedrock/docs/configuration-files/) I think there's probably sufficient info there.

**Pull request closed without merging**
