### PR TITLE
Look for a .env.local for specific overrides.

### PR DESCRIPTION
**Pull request by trsteel88**
This is a different approach to override ENV variables (one that the Symfony framework follows).

Rather than executing a script from composer.json, .env becomes the default (and is committed).

Then, if you want to override specific variables, you would create a .env.local on the relevant environment. The .env.local is not committed.

This also solves an issue where ENV variables don't exist. e.g. if a dev creates a new ENV variable in .env.example. This isn't automatically appended to any other developers .env variables.

If they were to commit .env with a suitable default, then any other developers using the codebase will automatically use the suitable default defined.

### CODE REVIEW

**Comment by swalkinshaw** [comment]
🤔 I like parts of this idea.

Though overall I find it a bit weird to have a `.env` file committed with useless values. They aren't useful defaults, they're placeholders that *have* to be replaced. Usually the config model of having a `.local` override is for actual overrides.

@austinpray what do you think

**Comment by JulienMelissas** [comment]
👍 to having a local override option, 👎  to committing the `.env`... that seems like a violation of best practices IMO.

**Comment by MWDelaney** [comment]
`.env` is a build artifact. We shouldn't commit it.

**Comment by trsteel88** [comment]
I wouldn't say they are useless defaults. The idea would be that you would put useful defaults in there and then if something needed to be reconfigured you would add it to the .env.local

I find it strange that .env.example is automatically copied to .env during a composer install.

If a developer creates a new ENV var then anyone who already has the project setup won't automatically get these variables which could then cause an exception in the application.

**Comment by TangRufus** [comment]
I vote for following `vlucas/phpdotenv`'s expected [usage](https://github.com/vlucas/phpdotenv#usage-notes) plus allowing `.env.local` to override Trellis generated `.env`, i.e:
- keep `.env` git ignored
- keep `.env.example`
- remove https://github.com/roots/bedrock/blob/3dbfaec8b5c42d88cf401b80c291bbbad10991d9/composer.json#L62-L63
- load `.env.local` if exist
  ```diff
  - $dotenv = Dotenv\Dotenv::createUnsafeImmutable($root_dir);
  + $dotenv = Dotenv\Dotenv::createUnsafeImmutable($root_dir, ['.env', '.env.local'], false);
  ```


Use case:
Overriding DB credentials when using valet, local DB and `$ trellis dotenv`. So that my teammates are not required to follow my [db_password](https://github.com/roots/trellis/blob/17430191bb7211545eb63ba3ba989ee95c262c5f/group_vars/development/vault.yml#L10).

**Comment by trsteel88** [comment]
Here is another solution: https://github.com/roots/bedrock/pull/587

Don't commit .env and just load .env.example first. If .env exists it will override project defaults.

**Comment by swalkinshaw** [comment]
@trsteel88 thanks for proposing this and getting us thinking. https://github.com/roots/bedrock/pull/595 and https://github.com/roots/bedrock/pull/594 are the changes that will come out of all this discussion

**Pull request closed without merging**
