### PR TITLE
Fix URL issues on multisite (especially in network admin)

### LINKED ISSUE #250: URL issues on multisite
I have recently set up my first multisite with Bedrock, and I have encountered several issues where the URLs are not correct. After some investigation, I figured that the issues are a result of a problem in WordPress Core - in some places it does not honor the site URL setting. This is no problem with a regular WP install, but when WordPress is installed in a subdirectory as it is in Bedrock, the site URL is different from the home URL.

The most significant problem is that some areas in the network admin will direct me to /wp-admin instead of /wp/wp-admin, for example when you're on the My Sites section and click on "Edit Site".

To be clear, this is not a Bedrock bug, but I think it would be great if Bedrock provided a fix for it, so that other people do not run into this problem. While there are ways to workaround this with nginx / htaccess rewrites, I'd prefer to actually fix it from the code site. As of now, I have fixed these issues on my site, so I'll create a pull-request with my approach.

Btw I also created a ticket on Core Trac, the first responses told me that WP doesn't officially support this - so not sure whether there will be a Core fix soon.

### PR DESCRIPTION
**Pull request by felixarntz**
This fixes #250

### CODE REVIEW

**Comment by swalkinshaw** [comment]
Thanks for sharing this @felixarntz. Just wanted to reply that I'm not sure if we want to provide extra code in Bedrock to fix this yet.

I'll leave this open for the time being but it would also need testing and hopefully other people who have more Multisite experience than me can chime in as well.

**Comment by reverbsoul** [comment]
Thanks for this @felixarntz - been looking for this fix for a while.

**Comment by oxyc** [comment]
No extensive testing done but so far so good–all the URLs seem to be fixed with this PR.

**Comment by xyNNN** [comment]
What's the state of this PR?

**Comment by swalkinshaw** [comment]
I don't have enough multisite experience to merge this without knowing the implications yet.

But this PR also won't be merged regardless until it passes our coding standards (see CI failures for details).

**Comment by cfxd** [comment]
Hey @felixarntz thanks for this PR. I'd love to see this pass build checks. That would be one step closer to a merge and fix of this issue which affects both Bedrock and Trellis (https://github.com/roots/trellis/pull/616).

**Comment by swalkinshaw** [comment]
I think this should be a separate plugin/package. Although the problem happens with Bedrock, it's a WP but not a Bedrock one.

If this was a standalone package, Bedrock could require or at least recommend it.

**Comment by amenk** [comment]
@felixarntz did this fix all issues? are you working on a standalone package?

**Comment by lekkerduidelijk** [comment]
The PR #276 by @ryanplasma fixed my issues. It's a small mu-plugin file. 👏

**Comment by JulienMelissas** [comment]
Just for reference purposes, https://github.com/roots/multisite-url-fixer should now help with this.

**Pull request closed without merging**
