### PR TITLE
DRY up environment configs

### PR DESCRIPTION
**Pull request by swalkinshaw**
No point in repeating these settings in every env config since it's all the same, so we'll move them to `application.php`.

### CODE REVIEW

**Comment by QWp6t** [comment]
I'd load environment php files first. Then conditionally define each of these, like so...

```php
 /**
 * URLs
 */
defined('WP_HOME') || define('WP_HOME', getenv('WP_HOME'));
defined('WP_SITEURL') || define('WP_SITEURL', getenv('WP_SITEURL'));
```

**Comment by swalkinshaw** [comment]
@QWp6t environment files are loaded before anything else.

**Comment by QWp6t** [comment]
Ahh, cool. My suggestion to conditionally define each constant still stands, though. I think it would be a good idea to let developers define stuff in their environment php files *if they want to*. They might need to apply some sort of logic to determine how the constants are defined in certain environments, but not in other environments.

In fact, I'd make that suggestion for every defined constant in application.php.


Up at the top of application.php, I suggest the following...
```php
<?php namespace Bedrock;

function define($name, $value) {
  defined($name) || \define($name, $value);
}

// ...
```

**Comment by swalkinshaw** [comment]
Right now we just kind of punt on it and mention it in the `README`:

> Note: You can't re-define constants in PHP. So if you have a base setting in application.php and want to override it in production.php for example, you have a few options:

> Remove the base option and be sure to define it in every environment it's needed
Only define the constant in application.php if it isn't already defined.

Just not sure about namespacing the config and providing on our `define`.

Going to merge this as is for now and we can thin about your solution separately.

**Pull request merged**
