### PR TITLE
Display correct bedrock-autoloader version

### PR DESCRIPTION
**Pull request by chrillep**
https://github.com/roots/bedrock/blob/8df74d1dfdd60953db939ac7cbd3d134310aa863/composer.lock#L342-L343

Maybe there is a better way of fetching version from lockfile or adding it to roots/bedrock-autoloader per default. But until then...

### CODE REVIEW

**Comment by tangrufus** [comment]
Or, we can just remove the `Version` line from plugin header.

**Comment by chrillep** [comment]
> Or, we can just remove the `Version` line from plugin header.

i just happend to stumble upon this when i was looking for something else. :)

**Comment by retlehs** [comment]
Good idea @tangrufus :+1:

@chrillep Are you not open to iterating on this PR after receiving feedback? If so, just close it.

**Comment by chrillep** [comment]
> Good idea @tangrufus 👍
> 
> @chrillep Are you not open to iterating on this PR after receiving feedback? If so, just close it.

sorry went on vacation.

I removed the Version line from plugin header.

**Pull request merged**
