### PR TITLE
Suport correct mapping under Multidomain multisites

### PR DESCRIPTION
**Pull request by Qoto**
Allows correct representaion of URLs under mutlisite setups in regards with media uploads and plugins

### CODE REVIEW

**Comment by retlehs** [comment]
sounds like an issue with your multisite setup. this isn't necessary

**Comment by Qoto** [comment]
@retlehs this is to support the MU Domain Mapping plugin with mapped subdomains on LEMH setups. This is confirmed by 4 different installations.
You also have #58 as reference.

**Comment by SamuelTissot** [comment]
thanks for the update, really appreciate it.

Sam

**Comment by retlehs** [comment]
what is there to reference in #58 regarding this? bedrock isn't going to add the code in this PR...

**Comment by alexbogias** [comment]
I don't know why this wasn't merged. Lost 3 days of trying a lot of workarounds and finally this solved my problem with attachment urls for each domain. Good Job @Qoto

**Pull request closed without merging**
