### PR TITLE
travis: PHP 7.0 nightly added

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by Foxaii** [comment]
Do you mind changing this to 'nightly' and rebasing to keep consistency with roots/sage#1355

Thanks!

**Comment by TomasVotruba** [comment]
I haven't notices it's the same organization. Fixed!

**Comment by swalkinshaw** [comment]
Thanks!

**Comment by TomasVotruba** [comment]
Thank you!

**Pull request merged**
