### PR TITLE
Add Docker

### PR DESCRIPTION
**Pull request by SalvadorCardona**
Work for add a local dev docker with container : 
- Maildev for catch mail on port 8080
- PhpAdmin on port 8081
- Nginx  on port 80
- PHP 8.0 & Xdebug 3
- Mysql

For starting : 
- cp .env.example .env
- change WP_HOME='http://example.com' to WP_HOME='http://localhost' in .env
- docker-compose up

This docker configuration is not ready for production, only use for dev

### CODE REVIEW

**Comment by ethanclevenger91** [comment]
Love this idea. Built something similar, slightly more lightweight, that compliments Bedrock well. Based on Laravel Sail. https://github.com/sterner-stuff/wordpress-sail

**Comment by MikeiLL** [comment]
Does seem like it could be useful.

**Comment by SalvadorCardona** [comment]
> Love this idea. Built something similar, more lightweight, that compliments Bedrock well. Based on Laravel Sail. [sterner-stuff/wordpress-sail](https://github.com/sterner-stuff/wordpress-sail)

No problem and have a nice day :)

**Comment by AlejandroAkbal** [comment]
I think this should be reopened

Docker is an amazing tool for deploying code

**Comment by MikeiLL** [comment]
> I think this should be reopened
> 

To be fair, though, this is already a fairly complex ecosystem to maintain.

**Pull request closed without merging**
