### PR TITLE
use ~ operator on composer requirements

### PR DESCRIPTION
**Pull request by thewunder**
This commit uses the ~ operator on composer requirements so that composer upgrade grabs the latest bugfixes etc...

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
Worth noting [4.0.1 broke some plugins due to bad plugin dev practices](http://wptavern.com/wordpress-4-0-1-exposes-bad-development-practices-used-in-some-plugins). Not sure we want composer to auto upgrade that.

**Comment by austinpray** [comment]
Definitely no `~` on wordpress. Wordpress does not follow semver anyway.

**Comment by swalkinshaw** [comment]
@thewunder I'm fine with `~` for the non WP packages if you want to update this.

**Comment by thewunder** [comment]
The composer.lock file will prevent it from being automatically upgraded without testing...

I'm mostly a Symfony dev not a wordpress dev, so if you don't think it's safe I'll remove.

**Comment by jaywilliams** [comment]
This is the way I have mine setup, actually. Composer locks the version, so any version change can easily be reverted.

**Comment by swalkinshaw** [comment]
@thewunder sorry kind of forgot about this. Would you be able to rebase it so it can be merged?

**Comment by thewunder** [comment]
Rebased

**Comment by retlehs** [comment]
@thewunder not actually rebased FYI (shouldn't be showing 13 commits on this PR, just 1)

**Comment by thewunder** [comment]
That's what happens when you use phpstorms rebase, it copied the commits...

Used git push --force for the first time ever :boom:

**Comment by swalkinshaw** [comment]
Thanks!

**Comment by M13Kd** [comment]
@M13Kd

-------- Original message --------

**Pull request merged**
