### PR TITLE
.env

### PR DESCRIPTION
**Pull request by nabsalz**
database update

### CODE REVIEW

**Comment by nabsalz** [comment]
admin

**Comment by QWp6t** [comment]
Having trouble there, buddy?

**Comment by nabsalz** [comment]
update my database info in .env fileand accept my pull request

**Comment by QWp6t** [comment]
You have your own repo, man. Why you wanna hijack ours too? Stop tryna hoard all the repos!! :rage:

(To clarify: You don't have to submit a pull request when you make changes to your own repo. Only submit PRs when you're actually trying to push an upstream change to Bedrock. Your modifications in this PR are obviously specific to the job you've been contracted to do. They don't belong in our repo, only yours. Hope it helps!)

**Pull request closed without merging**
